### PR TITLE
Ranges and blocks

### PR DESCRIPTION
**Pull request by nrc**

### CODE REVIEW

**Comment by bkchr** [comment]
LGTM

**Comment by gbutler69** [comment]
Does it not increase readability when splitting a line at operators to have the split before the operator as opposed to after. For example:

````rust
    let result = some_really_really_really_really_really_really_really_long_expression
               + some_other_expresssion;
````
versus
````rust
    let result = some_really_really_really_really_really_really_really_long_expression +
                 some_other_expresssion;
````

So, for this example:

````rust
   a_long_long_long_long_long_long_long_long_long_long_long_expression..
       another_long_expression
````

Wouldn't it be more readable as:

````rust
   a_long_long_long_long_long_long_long_long_long_long_long_expression
   ..another_long_expression
````

Personally, I always prefer operators to be at the beginning of the line like this. It makes it easy to scan vertically for operators. Just a thought.

**Comment by joshtriplett** [comment]
@gbutler69 That is a reasonable thought. We already break before binary operators in all other cases. Treating the range operator the same way seems entirely reasonable to me.

@nrc Any objections to that change?

**Comment by nrc** [comment]
Seems good to me, to be clear, I'd keep the indent:
```
   a_long_long_long_long_long_long_long_long_long_long_long_expression
       ..another_long_expression
```

**Comment by joshtriplett** [comment]
@nrc Agreed. We should format it identically to how we would with any other binary operator, other than leaving out the whitespace between the operator and the following expression.

**Pull request merged**
